export default {
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "auto",
  insertPragma: false,
  jsxSingleQuote: true,
  printWidth: 80,
  proseWrap: "always",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: true,
  singleAttributePerLine: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
  vueIndentScriptAndStyle: false,
  overrides: [
    {
      files: ["*.json", ".eslintrc"],
      options: { tabWidth: 2, trailingComma: "none" },
    },
  ],
  plugins: ["@trivago/prettier-plugin-sort-imports"],
  importOrder: [
    "^react(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@/(.*)$",
    "^\\.\\.(?:/|$)",
    "^\\.(?:/|$)",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
